Send preference settings content
DynamoDS/SplashScreen pull request #9
Opened 2022-10-13 13:48 UTC by filipeotero

This PR includes a change for the implementation of the import settings method. 
Now we are sending the content of the file instead of the file object.
It's also included in this PR a fix that was occurring with the loading bar when we tried to update the size.

2022-10-13 15:28 UTC, avidit requested changes
Can you please run `npm run lini:check`
It seems there are duplications during a merge conflict.

2022-10-13 19:23 UTC, QilongTang commented on src/Dynamic.js
> +  render() {
agreed, this particular one is duplicate

2022-10-14 15:51 UTC, avidit approved these changes

2022-10-14 18:14 UTC, QilongTang commented
@avidit The error is that the code coverage is too low, is it safe to ignore for now?

2022-10-14 18:30 UTC, merged